### ISSUE TITLE
Broken with Jasmine 2.5.0?

### ISSUE THREAD

**Issue by alxhub** [sindresorhus/gulp-jasmine#84] opened 2016-08-31 17:27 UTC
When running gulp-jasmine with the newly released Jasmine 2.5.0, my gulp task of the form:

```
gulp.task('name', function() {
  return gulp.src(['...']).pipe(gulpJasmine());
});
```

never actually completes. With Jasmine 2.4.x, it works as expected. I'm not sure if this is a bug or intentional change in the way Jasmine works that will require a fix in gulp-jasmine.

My actual gulp task that fails when Jasmine is upgraded is: https://github.com/angular/mobile-toolkit/blob/0b0df9b0d8d2674db405b0854096ed61fb791bf3/service-worker/worker/gulpfile.ts#L374

Thanks!

**Comment by lrbridge** [comment] 2016-08-31 22:09
+1
Our builds all starting failing today when our gulp build started silently stopping during our gulp-jasmine tasks... npm-shrinkwrapping to jasmine 2.4.1 fixed the isseu

**Comment by jbblanchet** [comment] 2016-09-01 00:15
Thanks for reporting this. I'll try to have a look tomorrow morning.

**Comment by thoean** [comment] 2016-09-01 12:44
We are facing the same problem. It looks like the problem is related to https://github.com/jasmine/jasmine-npm/blob/master/lib/jasmine.js#L163, which passes by default and exits the whole nodejs process. Probably gulp-jasmine needs to configure it's own `onComplete` method to not get into this if-condition?

Unfortunately I'm not familiar enough with the exact internals and how it worked before, so I don't feel confident to work towards a pull request myself.

**Comment by jbblanchet** [comment] 2016-09-01 12:49
If that's the case, #83 should fix this issue. It's merged, but wasn't released yet. If anyone could test that it fixes the problem, that would be a huge help.

Thanks.

**Comment by thoean** [comment] 2016-09-01 13:28
I've copied your changes into my local package, and it fixes the problem that the nodejs process gets exited. From that perspective, it should be good.

However, I have a follow up error of the `jasmineDone` reporter called too often, which results in an `Error: task completion callback called too many times` error.

**Comment by jbblanchet** [comment] 2016-09-01 13:59
I can confirm that #83 fixed this issue (that's pretty lucky, right?). I'll prepare a release.

@thoean I didn't have that issue with my very simple `expect(1).toBe(1)`, so it might be a different issue. If you're still seeing the problem after the release, I suggest opening another issue so we can look at it.

**Comment by jbblanchet** [comment] 2016-09-01 14:06
Fixed in 2.4.1.

**Closed by jbblanchet** 2016-09-01 14:06 UTC

**Comment by thoean** [comment] 2016-09-01 15:08
2.4.1 fixed the issue originally mentioned. So I believe this issue can be closed. Thanks a lot for the quick turn around.

I continue seeing the other problem. I see that a bit later after my next gulp-task starts. I use [run-sequence](https://github.com/OverZealous/run-sequence) to run multiple tasks, and after a few milliseconds after the next task starts, I get that error. Seems like the next task is already started before gulp-jasmine fully completed (or potentially before jasmine itself fully completed).

I will debug this at some point later and file a new ticket, potentially even towards another library.

**Comment by thoean** [comment] 2016-09-02 15:28
Update from my side: That was just a silly follow up error of trying to debug things. In addition to returning the "gulp jasmine pipe" I was also calling the callback of the gulp task in the `jamineDone` event.

Overall, thanks again for your quick turnaround on the main issue. That was really helpful.
